version: "3.6"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todos_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
      - ./app/db:/docker-entrypoint-initdb.d
  app:
    depends_on:
      - mysqldb
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=todos_db
      - DB_PORT=3306
    stdin_open: true
    tty: true

volumes:
  db:
