---
# tasks file for container-setup
- name: setup mysql container
  docker_container:
    image: mysql:5.7
    name: mysqldb
    state: started
    restart: unless- stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todos_db
    ports:
      - "3306:3306"
    volumes:
      - "db:/var/lib/mysql"
      - "./app/db:/docker-entrypoint-initdb.d"
- name: create build directory
  file:
    path: /root/demo-dockerfile
    state: directory
    owner: root
    group: root
    mode: '0755'
- name: copy Dockerfile
  copy:
    src: ./Dockerfile
    dest: /root/demo-dockerfile/Dockerfile
    owner: root
    group: root
    mode: '0644'
- name: build container image
  docker_image:
     name: democontainer:v1.0
     build:
      path: /root/demo-dockerfile
      source: build
    state: present
